spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tradedb
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


spring.kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: blocking-trade-consumer
    auto-offset-reset: earliest

springdoc:
  api-docs:
    path: /api/blocking-docs
  swagger-ui:
    path: /swagger-ui-blocking.html
