spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/tradedb
    username: postgres
    password: admin

spring.kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: reactive-trade-consumer
    auto-offset-reset: earliest

springdoc:
  api-docs:
    path: /api/reactive-docs
  swagger-ui:
    path: /swagger-ui-reactive.html
